version: 0.2

phases:
  install:
  
    commands:
      - echo "no install commands neccessary"
    
  pre_build:
    
    commands:
      - echo "no pre-build commands neccessary"
    
  build:
    
    commands:
      - echo "no build commands neccessary"
     
  post_build:
   
    commands:
      - echo "no post-build commands neccessary"

artifacts:

  files:
    - "index.html"
    - "buildspec.yml"
    - "README.md"
    - "images/*"
    - "style.css"
    
  
  