version: 0.2

phases:
  install:
  
    commands:
      - echo "no install commands neccessary"
    
  pre_build:
    
    commands:
      - echo "no pre-build commands neccessary"
    
  build:
    
    commands:
      - echo "no build commands neccessary"
     
  post_build:
   
    commands:
      - echo "Creating CloudFront invalidation for cloudfront staging distribution"
      - aws cloudfront create-invalidation --distribution-id E1JQINKCKYJWKY --paths "/*"
      - echo "Invalidation created for E1JQINKCKYJWKY (staging distribution)"
      - echo "Creating CloudFront invalidation for cloudfront standard distribution"
      - aws cloudfront create-invalidation --distribution-id E20DS1GI04NK08 --paths "/*"
      - echo "Invalidation created for E20DS1GI04NK08 (standard distribution)"
artifacts:

  files:
    - "index.html"
    - "buildspec.yml"
    - "README.md"
    - "images/*"
    - "style.css" 
    
  
  